In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import geopandas as gpd
import plotly.express as px

In [2]:
# https://hub.arcgis.com/datasets/esri::usa-counties/about

In [3]:
tract = gpd.read_file("USA_Counties.geojson")
tract.shape

(3143, 62)

In [4]:
tract.head()

,FID,NAME,STATE_NAME,STATE_FIPS,CNTY_FIPS,FIPS,POPULATION,POP_SQMI,POP2010,POP10_SQMI,...,AVE_SALE12,SQMI,NO_FARMS17,AVE_SIZE17,CROP_ACR17,AVE_SALE17,Shape_Leng,SHAPE_Length,SHAPE_Area,geometry
0,1,Autauga County,Alabama,01,001,01001,58224,96.3,54571,90.3,...,50929.0,604.37,371.0,305.0,36890.0,57844.0,2.066033,2.066033,0.150256,"MULTIPOLYGON (((-86.41312 32.70739, -86.41300 ..."
1,2,Baldwin County,Alabama,01,003,01003,227660,139.4,182265,111.1,...,137069.0,1633.14,842.0,208.0,110438.0,142972.0,9.305629,9.305629,0.398404,"MULTIPOLYGON (((-87.56491 30.28162, -87.56470 ..."
2,3,Barbour County,Alabama,01,005,01005,26326,29.1,27457,30.4,...,182761.0,904.52,498.0,307.0,37304.0,211977.0,2.695260,2.695260,0.223270,"MULTIPOLYGON (((-85.25784 32.14794, -85.25851 ..."
3,4,Bibb County,Alabama,01,007,01007,23066,36.8,22915,36.6,...,0.0,626.17,205.0,273.0,15823.0,20484.0,1.887519,1.887519,0.156473,"MULTIPOLYGON (((-87.06574 33.24691, -87.06477 ..."
4,5,Blount County,Alabama,01,009,01009,59970,92.2,57322,88.1,...,143586.0,650.63,1146.0,129.0,43793.0,211916.0,2.423466,2.423466,0.164405,"MULTIPOLYGON (((-86.45302 34.25932, -86.45288 ..."

In [5]:
tract.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 3143 entries, 0 to 3142
Data columns (total 62 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   FID           3143 non-null   int64
 1   NAME          3143 non-null   object
 2   STATE_NAME    3143 non-null   object
 3   STATE_FIPS    3143 non-null   object
 4   CNTY_FIPS     3143 non-null   object
 5   FIPS          3143 non-null   object
 6   POPULATION    3143 non-null   int64
 7   POP_SQMI      3143 non-null   float64
 8   POP2010       3143 non-null   int64
 9   POP10_SQMI    3143 non-null   float64
 10  WHITE         3143 non-null   int64
 11  BLACK         3143 non-null   int64
 12  AMERI_ES      3143 non-null   int64
 13  ASIAN         3143 non-null   int64
 14  HAWN_PI       3143 non-null   int64
 15  HISPANIC      3143 non-null   int64
 16  OTHER         3143 non-null   int64
 17  MULT_RACE     3143 non-null   int64
 18  MALES         3143 non-null   int64
 19  FEMALES       3143 non-null   int64
 20  AGE_UNDER5    3143 non-null   int64
 21  AGE_5_9       3143 non-null   int64
 22  AGE_10_14     3143 non-null   int64
 23  AGE_15_19     3143 non-null   int64
 24  AGE_20_24     3143 non-null   int64
 25  AGE_25_34     3143 non-null   int64
 26  AGE_35_44     3143 non-null   int64
 27  AGE_45_54     3143 non-null   int64
 28  AGE_55_64     3143 non-null   int64
 29  AGE_65_74     3143 non-null   int64
 30  AGE_75_84     3143 non-null   int64
 31  AGE_85_UP     3143 non-null   int64
 32  MED_AGE       3143 non-null   float64
 33  MED_AGE_M     3143 non-null   float64
 34  MED_AGE_F     3143 non-null   float64
 35  HOUSEHOLDS    3143 non-null   int64
 36  AVE_HH_SZ     3143 non-null   float64
 37  HSEHLD_1_M    3143 non-null   int64
 38  HSEHLD_1_F    3143 non-null   int64
 39  MARHH_CHD     3143 non-null   int64
 40  MARHH_NO_C    3143 non-null   int64
 41  MHH_CHILD     3143 non-null   int64
 42  FHH_CHILD     3143 non-null   int64
 43  FAMILIES      3143 non-null   int64
 44  AVE_FAM_SZ    3143 non-null   float64
 45  HSE_UNITS     3143 non-null   int64
 46  VACANT        3143 non-null   int64
 47  OWNER_OCC     3143 non-null   int64
 48  RENTER_OCC    3143 non-null   int64
 49  NO_FARMS12    3143 non-null   float64
 50  AVE_SIZE12    3143 non-null   float64
 51  CROP_ACR12    3143 non-null   float64
 52  AVE_SALE12    3143 non-null   float64
 53  SQMI          3143 non-null   float64
 54  NO_FARMS17    3143 non-null   float64
 55  AVE_SIZE17    3143 non-null   float64
 56  CROP_ACR17    3143 non-null   float64
 57  AVE_SALE17    3143 non-null   float64
 58  Shape_Leng    3143 non-null   float64
 59  SHAPE_Length  3143 non-null   float64
 60  SHAPE_Area    3143 non-null   float64
 61  geometry      3143 non-null   geometry
dtypes: float64(19), geometry(1), int64(37), object(5)
memory usage: 1.5+ MB

In [6]:
tract.columns

Index(['FID', 'NAME', 'STATE_NAME', 'STATE_FIPS', 'CNTY_FIPS', 'FIPS',
       'POPULATION', 'POP_SQMI', 'POP2010', 'POP10_SQMI', 'WHITE', 'BLACK',
       'AMERI_ES', 'ASIAN', 'HAWN_PI', 'HISPANIC', 'OTHER', 'MULT_RACE',
       'MALES', 'FEMALES', 'AGE_UNDER5', 'AGE_5_9', 'AGE_10_14', 'AGE_15_19',
       'AGE_20_24', 'AGE_25_34', 'AGE_35_44', 'AGE_45_54', 'AGE_55_64',
       'AGE_65_74', 'AGE_75_84', 'AGE_85_UP', 'MED_AGE', 'MED_AGE_M',
       'MED_AGE_F', 'HOUSEHOLDS', 'AVE_HH_SZ', 'HSEHLD_1_M', 'HSEHLD_1_F',
       'MARHH_CHD', 'MARHH_NO_C', 'MHH_CHILD', 'FHH_CHILD', 'FAMILIES',
       'AVE_FAM_SZ', 'HSE_UNITS', 'VACANT', 'OWNER_OCC', 'RENTER_OCC',
       'NO_FARMS12', 'AVE_SIZE12', 'CROP_ACR12', 'AVE_SALE12', 'SQMI',
       'NO_FARMS17', 'AVE_SIZE17', 'CROP_ACR17', 'AVE_SALE17', 'Shape_Leng',
       'SHAPE_Length', 'SHAPE_Area', 'geometry'],
      dtype='object')

In [7]:
tract.drop(columns=['FID', 'STATE_NAME', 'STATE_FIPS', 'CNTY_FIPS',
       'POPULATION', 'POP_SQMI', 'POP2010', 'POP10_SQMI', 'WHITE', 'BLACK',
       'AMERI_ES', 'ASIAN', 'HAWN_PI', 'HISPANIC', 'OTHER', 'MULT_RACE',
       'MALES', 'FEMALES', 'AGE_UNDER5', 'AGE_5_9', 'AGE_10_14', 'AGE_15_19',
       'AGE_20_24', 'AGE_25_34', 'AGE_35_44', 'AGE_45_54', 'AGE_55_64',
       'AGE_65_74', 'AGE_75_84', 'AGE_85_UP', 'MED_AGE', 'MED_AGE_M',
       'MED_AGE_F', 'HOUSEHOLDS', 'AVE_HH_SZ', 'HSEHLD_1_M', 'HSEHLD_1_F',
       'MARHH_CHD', 'MARHH_NO_C', 'MHH_CHILD', 'FHH_CHILD', 'FAMILIES',
       'AVE_FAM_SZ', 'HSE_UNITS', 'VACANT', 'OWNER_OCC', 'RENTER_OCC',
       'NO_FARMS12', 'AVE_SIZE12', 'CROP_ACR12', 'AVE_SALE12', 'SQMI',
       'NO_FARMS17', 'AVE_SIZE17', 'CROP_ACR17', 'AVE_SALE17', 'Shape_Leng',
       'SHAPE_Length'], axis=1, inplace=True)

In [8]:
tract.shape

(3143, 4)

In [9]:
tract['FIPS'] = pd.to_numeric(tract['FIPS']).astype('int64')

In [10]:
tract

,NAME,FIPS,SHAPE_Area,geometry
0,Autauga County,1001,0.150256,"MULTIPOLYGON (((-86.41312 32.70739, -86.41300 ..."
1,Baldwin County,1003,0.398404,"MULTIPOLYGON (((-87.56491 30.28162, -87.56470 ..."
2,Barbour County,1005,0.223270,"MULTIPOLYGON (((-85.25784 32.14794, -85.25851 ..."
3,Bibb County,1007,0.156473,"MULTIPOLYGON (((-87.06574 33.24691, -87.06477 ..."
4,Blount County,1009,0.164405,"MULTIPOLYGON (((-86.45302 34.25932, -86.45288 ..."
...,...,...,...,...
3138,Uinta County,56041,0.581330,"MULTIPOLYGON (((-110.96532 41.57946, -110.9245..."
3139,Washakie County,56043,0.650754,"MULTIPOLYGON (((-108.54727 44.16848, -108.5443..."
3140,Weston County,56045,0.695661,"MULTIPOLYGON (((-104.05450 44.18039, -104.0545..."
3141,Chugach Census Area,2063,4.258676,"MULTIPOLYGON (((-147.45994 59.84190, -147.4614..."
3142,Copper River Census Area,2066,11.118820,"MULTIPOLYGON (((-141.00219 61.90404, -141.0023..."

In [11]:
tract.to_file('counties.geojson', driver='GeoJSON')

In [12]:
tract.to_pickle('counties_pkl.pkl')